name: physical_demo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  go_router: 4.2.6
  get_it: 7.2.0
  freezed_annotation: 2.1.0
  injectable: 1.5.3
  loader_overlay: ^2.1.0
  lottie: 1.4.3
  validators: 3.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: 2.0.3+1
  build_runner: 2.1.11
  injectable_generator: 1.5.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/image/
